Pb4Blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Pb4Blog.views.home', name='home'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls')),
)

blog/urls.py
from django.conf.urls import patterns, include, url

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager

from django.contrib.auth.models import

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)
    tags = TaggableManager()

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('blog_post_detail', (),
                {'slug': self.slug, }
                )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    name = models.CharField(max_length=42)
    email = models.EmailField(max_length=75)
    website = models.URLField(max_length=200, null=True, blank=True)
    text = models.TextField()
    post = models.ForeignKey(Post)
    created_on = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.text

blog/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author', 'slug']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['post']

blog/views.py
from django.shortcuts import render

# Create your views here.

from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.template import RequestContext

from .models import Post
from .forms import PostForm, CommentForm

@user_passes_test(lambda u: u.is_superuser)
def add_post(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(post)
    return render_to_response('blog/add_post.htm',
                              {'form': form},
                              context_instance=RequestContext(request))


def view_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect(request.path)
    form.initial['name'] = request.session.get('name')
    form.initial['email'] = request.session.get('email')
    form.initial['website'] = request.session.get('website')
    return render_to_response('blog/blog_post.htm',
                              {
                                  'post': post,
                                  'form': form,
                              },
                              context_instance=RequestContext(request))

blog/templates/blog/add_post.htm
<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=Generator content="Microsoft Word 12 (filtered)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0in;
	margin-right:0in;
	margin-bottom:10.0pt;
	margin-left:0in;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
.MsoPapDefault
	{margin-bottom:10.0pt;
	line-height:115%;}
@page Section1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.Section1
	{page:Section1;}
-->
</style>

</head>

<body lang=EN-US>

<div class=Section1>

<p class=MsoNormal>&lt;h2&gt;Hello {{ user.username }}&lt;/h2&gt;</p>

<p class=MsoNormal>&lt;br /&gt;</p>

<p class=MsoNormal>&lt;h2&gt;Add new post&lt;/h2&gt;</p>

<p class=MsoNormal>&lt;form action=&quot;&quot; method=&quot;POST&quot;&gt;</p>

<p class=MsoNormal>    {% csrf_token %}</p>

<p class=MsoNormal>    &lt;table&gt;</p>

<p class=MsoNormal>        {{ form.as_table }}</p>

<p class=MsoNormal>    &lt;/table&gt;</p>

<p class=MsoNormal>    &lt;input type=&quot;submit&quot; name=&quot;add&quot;
value=&quot;Add&quot; /&gt;</p>

<p class=MsoNormal>&lt;/form&gt;</p>

</div>

</body>

</html>

blog/templates/blog/blog_post.htm
<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=Generator content="Microsoft Word 12 (filtered)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0in;
	margin-right:0in;
	margin-bottom:10.0pt;
	margin-left:0in;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
.MsoPapDefault
	{margin-bottom:10.0pt;
	line-height:115%;}
@page Section1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.Section1
	{page:Section1;}
-->
</style>

</head>

<body lang=EN-US>

<div class=Section1>

<p class=MsoNormal>&lt;h2&gt;{{ post.title }}&lt;/h2&gt;</p>

<p class=MsoNormal>&nbsp;</p>

<p class=MsoNormal>&lt;div class=&quot;content&quot;&gt;</p>

<p class=MsoNormal>    &lt;p&gt;</p>

<p class=MsoNormal>        {{ post.text }}</p>

<p class=MsoNormal>    &lt;/p&gt;</p>

<p class=MsoNormal>    &lt;span&gt;</p>

<p class=MsoNormal>        Written by {{ post.author }}  on {{ post.created_on
}}</p>

<p class=MsoNormal>    &lt;/span&gt;</p>

<p class=MsoNormal>&lt;/div&gt;</p>

<p class=MsoNormal>&nbsp;</p>

<p class=MsoNormal>{% if post.comment_set.all %}</p>

<p class=MsoNormal>&lt;h2&gt;Comments&lt;/h2&gt;</p>

<p class=MsoNormal>&lt;div class=&quot;comments&quot;&gt;</p>

<p class=MsoNormal>    {% for comment in post.comment_set.all %}</p>

<p class=MsoNormal>        &lt;span&gt;</p>

<p class=MsoNormal>            &lt;a href=&quot;{{ comment.website
}}&quot;&gt;{{ comment.name }}&lt;/a&gt; said on {{ comment.created_on }}</p>

<p class=MsoNormal>        &lt;/span&gt;</p>

<p class=MsoNormal>        &lt;p&gt;</p>

<p class=MsoNormal>            {{ comment.text }}</p>

<p class=MsoNormal>        &lt;/p&gt;</p>

<p class=MsoNormal>    {% endfor %}</p>

<p class=MsoNormal>&lt;/div&gt;</p>

<p class=MsoNormal>{% endif %}</p>

<p class=MsoNormal>&nbsp;</p>

<p class=MsoNormal>&lt;br /&gt;</p>

<p class=MsoNormal>&nbsp;</p>

<p class=MsoNormal>&lt;h2&gt;Add Comment&lt;/h2&gt;</p>

<p class=MsoNormal>&nbsp;</p>

<p class=MsoNormal>&lt;form action=&quot;&quot; method=&quot;POST&quot;&gt;</p>

<p class=MsoNormal>    {% csrf_token %}</p>

<p class=MsoNormal>    &lt;table&gt;</p>

<p class=MsoNormal>        {{ form.as_table }}</p>

<p class=MsoNormal>    &lt;/table&gt;</p>

<p class=MsoNormal>    &lt;input type=&quot;submit&quot;
name=&quot;submit&quot; value=&quot;Submit&quot; /&gt;</p>

<p class=MsoNormal>&lt;/form&gt;</p>

</div>

</body>

</html>